name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # OPPO
  ## Oneplus
  build-xiaomi-10s-miui-a13:
    name: "Build Xiaomi 10s (HyperOS A13)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-xiaomi-10s-miui-a13.yml
    secrets: inherit
